name: Create Pull Request from main_backend to main

on:
  push:
    branches:
      - main_backend

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        head: main_backend
        title: 'Automated PR from main_backend to main'
        body: 'This is an automated pull request created by GitHub Actions.'