name: Create Pull Request from main_backend to main

on:
  push:
    branches:
      - deploy_backend

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Generate unique title and body
      id: pr-info
      run: |
        TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
        echo "PR_TITLE=Merge branch_to_merge into main_backend_branch on $TIMESTAMP" >> $GITHUB_ENV
        echo "PR_BODY=Created by GitHub action on $TIMESTAMP" >> $GITHUB_ENV

    - name: Create pull request
      run: gh pr create -B main_backend -H deploy_backend --title "$PR_TITLE" --body "$PR_BODY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
