name: Create Pull Request from main_backend to main

on:
  push:
    branches:
      - b1

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: extrace git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    #- name: Create pull request
    #  uses: peter-evans/create-pull-request@v3
    #  with:
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    base: main
    #    head: b1
    #    title: 'Automated PR from main_backend to main'
    #    body: 'This is an automated pull request created by GitHub Actions.'
    - name: create pull request
      run: gh pr create -B main -H b1 --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}